[programs.localnet]
lumi = "BPDM9Ls3NU3JohLeTxxULbZzK4yUmqt5H2mRUCTms3R7"

[programs.devnet]
lumi = "BPDM9Ls3NU3JohLeTxxULbZzK4yUmqt5H2mRUCTms3R7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.32.1"

[scripts]
setup = "ts-node -O '{\"module\":\"commonjs\"}' ./tests/setup.ts"
